// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {scheduler} from '../models';

export function AddAppConfig(arg1:config.AppConfigItem):Promise<void>;

export function GetADKConfig():Promise<Record<string, any>>;

export function GetAIConfig():Promise<config.AIConfig>;

export function GetAlertConfig():Promise<config.AlertConfig>;

export function GetAppConfig(arg1:string):Promise<config.AppConfigItem>;

export function GetApps():Promise<Record<string, any>>;

export function GetBarrageConfig():Promise<config.BarrageConfig>;

export function GetCameraDetections(arg1:number,arg2:number):Promise<Record<string, any>>;

export function GetCameraGuardConfig():Promise<config.CameraGuardConfig>;

export function GetFullConfig():Promise<Record<string, any>>;

export function GetLangfuseConfig():Promise<config.LangfuseConfig>;

export function GetMessageStats():Promise<Record<string, any>>;

export function GetMessages(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function GetPrompt(arg1:string):Promise<Record<string, string>>;

export function GetPrompts():Promise<Record<string, any>>;

export function GetSkins():Promise<Record<string, any>>;

export function GetTasks():Promise<Record<string, any>>;

export function ImportSkin(arg1:string,arg2:string):Promise<Record<string, string>>;

export function ReloadConfig():Promise<void>;

export function RemoveAppConfig(arg1:string):Promise<void>;

export function SaveADKConfig(arg1:Record<string, any>):Promise<void>;

export function SaveAIConfig(arg1:config.AIConfig):Promise<void>;

export function SaveAlertConfig(arg1:config.AlertConfig):Promise<void>;

export function SaveAppConfig(arg1:string,arg2:config.AppConfigItem):Promise<void>;

export function SaveBarrageConfig(arg1:config.BarrageConfig):Promise<void>;

export function SaveCameraGuardConfig(arg1:config.CameraGuardConfig):Promise<void>;

export function SaveLangfuseConfig(arg1:config.LangfuseConfig):Promise<void>;

export function SavePrompt(arg1:string,arg2:string):Promise<void>;

export function SearchMessages(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SetScheduler(arg1:scheduler.Scheduler):Promise<void>;

export function SetSkin(arg1:string):Promise<void>;

export function TriggerTask(arg1:string):Promise<Record<string, string>>;
