// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAppConfig(arg1) {
  return window['go']['settings']['App']['AddAppConfig'](arg1);
}

export function GetADKConfig() {
  return window['go']['settings']['App']['GetADKConfig']();
}

export function GetAIConfig() {
  return window['go']['settings']['App']['GetAIConfig']();
}

export function GetAlertConfig() {
  return window['go']['settings']['App']['GetAlertConfig']();
}

export function GetAppConfig(arg1) {
  return window['go']['settings']['App']['GetAppConfig'](arg1);
}

export function GetApps() {
  return window['go']['settings']['App']['GetApps']();
}

export function GetBarrageConfig() {
  return window['go']['settings']['App']['GetBarrageConfig']();
}

export function GetCameraDetections(arg1, arg2) {
  return window['go']['settings']['App']['GetCameraDetections'](arg1, arg2);
}

export function GetCameraGuardConfig() {
  return window['go']['settings']['App']['GetCameraGuardConfig']();
}

export function GetFullConfig() {
  return window['go']['settings']['App']['GetFullConfig']();
}

export function GetLangfuseConfig() {
  return window['go']['settings']['App']['GetLangfuseConfig']();
}

export function GetMessageStats() {
  return window['go']['settings']['App']['GetMessageStats']();
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['settings']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetPrompt(arg1) {
  return window['go']['settings']['App']['GetPrompt'](arg1);
}

export function GetPrompts() {
  return window['go']['settings']['App']['GetPrompts']();
}

export function GetSkins() {
  return window['go']['settings']['App']['GetSkins']();
}

export function GetTasks() {
  return window['go']['settings']['App']['GetTasks']();
}

export function ImportSkin(arg1, arg2) {
  return window['go']['settings']['App']['ImportSkin'](arg1, arg2);
}

export function ReloadConfig() {
  return window['go']['settings']['App']['ReloadConfig']();
}

export function RemoveAppConfig(arg1) {
  return window['go']['settings']['App']['RemoveAppConfig'](arg1);
}

export function SaveADKConfig(arg1) {
  return window['go']['settings']['App']['SaveADKConfig'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['settings']['App']['SaveAIConfig'](arg1);
}

export function SaveAlertConfig(arg1) {
  return window['go']['settings']['App']['SaveAlertConfig'](arg1);
}

export function SaveAppConfig(arg1, arg2) {
  return window['go']['settings']['App']['SaveAppConfig'](arg1, arg2);
}

export function SaveBarrageConfig(arg1) {
  return window['go']['settings']['App']['SaveBarrageConfig'](arg1);
}

export function SaveCameraGuardConfig(arg1) {
  return window['go']['settings']['App']['SaveCameraGuardConfig'](arg1);
}

export function SaveLangfuseConfig(arg1) {
  return window['go']['settings']['App']['SaveLangfuseConfig'](arg1);
}

export function SavePrompt(arg1, arg2) {
  return window['go']['settings']['App']['SavePrompt'](arg1, arg2);
}

export function SearchMessages(arg1, arg2, arg3) {
  return window['go']['settings']['App']['SearchMessages'](arg1, arg2, arg3);
}

export function SetScheduler(arg1) {
  return window['go']['settings']['App']['SetScheduler'](arg1);
}

export function SetSkin(arg1) {
  return window['go']['settings']['App']['SetSkin'](arg1);
}

export function TriggerTask(arg1) {
  return window['go']['settings']['App']['TriggerTask'](arg1);
}
